### ISSUE TITLE
check option behaves strangely

### ISSUE THREAD

**Issue by degremont** [cea-hpc/milkcheck#11]
If you describe a `check` action between two actions, the 'check link' will be followed in the 2 ways, but it should be done only once.

```
service:
  actions:
    status:
       cmd: ...
    start:
       check: [ status ]
       cmd: ...
```

if you run start, status will be check before
if you run status, start will be also run.
