### ISSUE TITLE
Rename 'before' by 'after' to be coherent with require

### ISSUE THREAD

**Issue by cedeyn** [cea-hpc/milkcheck#19]
To define a service that requires another, we define the following milkcheck configuration:

```
services:
    a:
        require: b
        cmd: /bin/true
    b:
        cmd: /bin/true
```

That means a require b.

But with before:

```
services:
    a:
        before: b
        cmd: /bin/true
    b:
        cmd: /bin/true
```

That means b must be launch before a.

Renaming 'before' by 'after' would be more clear and coherent with the 'require' keyword:

``` YAML
services:
    a:
        after: b
        cmd: /bin/true
    b:
        cmd: /bin/true
```

That means a must be launch after b.
