### ISSUE TITLE
Threshold support for error and warning

### ISSUE THREAD

**Issue by cedeyn** [cea-hpc/milkcheck#20]
It could be nice to have thresholds to determine if a service is on WARNING or ERROR.

The current behaviour is 
- If the dependency is require and at least one node status is ERROR the service is ERROR
- WARNING is not used

The number of node should be customizable and milkcheck will be able to return a WARNING or an ERROR status.

configuration example:

``` yaml
service:
    name: a
    threshold: 4
    actions:
        status:
            cmd: /bin/true
```

If more than 4 nodes status is ERROR, then return ERROR.
If less than 4 nodes and at least 1 node status is ERROR, then return WARNING.
If no error return 0K.
