### ISSUE TITLE
Retcode not properly forwarded through Skipped services

### ISSUE THREAD

**Issue by fihuer** [cea-hpc/milkcheck#34]
Hi,
Here's a bug report about an incorrect return code when a requirement of a skipped service fails.

Cheers,
Romain F.

## Configuration file
```yaml
---
services:
  entry_point:
     desc: "Dummy entry point"
     require: [ action_successful_on_node2000 ]
     target: "node2000"
     actions:
        'status':
           cmd: /bin/true

  action_successful_on_node2000:
     desc: "Action only successful on node2000"
     target: "@contains_node2000"
     actions:
         'status':
           cmd: '[[ $HOSTNAME == "node2000" ]]'
```

## Expected behavior
- `milkcheck -n node2000 entry_point status` should return 0
- `milkcheck -n node2000 status` should return 0
- `milkcheck -n node2001 entry_point status` should return 6
- `milkcheck -n node2001 status` should return 6

## Current behavior
- [:+1:] `milkcheck -n node2000 entry_point status` returns 0
- [:+1:] `milkcheck -n node2000 status` should returns 0
- [:-1:] `milkcheck -n node2001 entry_point status` returns 0
<details>
  <summary>Debug output</summary>
<pre>
# milkcheck --debug -c . -n node2001 entry_point status
[11:41:13] DEBUG    - Configuration
nodeps: False
dryrun: False
verbosity: 5
only_nodes: node2001
summary: False
fanout: 128
reverse_actions: ['stop']
debug: True
config_dir: .
status action_successful_on_node2000 on node2001
 > [[ $HOSTNAME == "node2000" ]]
status action_successful_on_node2000 ran in 0.21 s
 > node2001 exited with 1
action_successful_on_node2000 - Action only successful on node2000                                         [  ERROR  ]
entry_point - Dummy entry point                                                                            [ SKIPPED ]
# echo $?
0
</pre>
</p></details>

- [:-1:] `milkcheck -n node2001 status`return 0

<details>
  <summary>Debug output</summary>
<pre>
#milkcheck --debug -c . -n node2001 status
[11:41:56] DEBUG    - Configuration
nodeps: False
dryrun: False
verbosity: 5
only_nodes: node2001
summary: False
fanout: 128
reverse_actions: ['stop']
debug: True
config_dir: .
status action_successful_on_node2000 on node2001
 > [[ $HOSTNAME == "node2000" ]]
status action_successful_on_node2000 ran in 0.21 s
 > node2001 exited with 1
action_successful_on_node2000 - Action only successful on node2000                                         [  ERROR  ]
entry_point - Dummy entry point                                                                            [ SKIPPED ]
# echo $?
0
</pre>
</p></details>

## Details
```
# milkcheck --version
milkcheck 1.0
# rpm -q milkcheck
milkcheck-1.0-4.el7.centos.noarch
# uname -a
Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.2.1511",
    major => "7",
    minor => "2"
  },
  selinux => {
    enabled => false
  }
}
```
