### ISSUE TITLE
Add a filtering dependency based on error nodes

### ISSUE THREAD

**Issue by degremont** [cea-hpc/milkcheck#6]
When a service A depends on another service B which partially failed (meaning, some nodes succeeded, some failed), the whole service A will be skipped (DEP_ERROR) even if the action could proceed on the successful nodes, at least

We will add a new dependency (we need a name for it 'filter'?) which will automatically exclude the fail nodes from the dep target.
Exemple:

```
services:
   foo:
       target: a[1-10]
       actions: ...
    bar:
       target: a[1-10]
       filter: foo
       actions: ...
```

If service foo failed for node a1 and succeeded for the other ones, a1 will automatically be excluded from target list of bar before bar is launched.
