### ISSUE TITLE
Exclude of subservice seems to be not working

### ISSUE THREAD

**Issue by MarbolanGos** [cea-hpc/milkcheck#62]
Hello,

Here is a case I am facing using milkcheck:
```
# milkcheck -c $PWD test -n lrdn0001
service1.subservice2                                                    [    OK   ]
service1.subservice1                                                    [    OK   ]
service1                                                                [    OK   ]
service2                                                                [    OK   ]
# milkcheck -c $PWD test -n lrdn0001 -X service1
service2                                                                [    OK   ]
# milkcheck -c $PWD test -n lrdn0001 -X service1.subservice1
service1.subservice2                                                    [    OK   ]
service1.subservice1                                                    [    OK   ]
service1                                                                [    OK   ]
service2                                                                
```

In the scond exclusion, I wanted the service1.subservice1 not to be run. Do you think it is possible?

My test file is:
```yaml
---
services:
   service1:
      timeout: 5
      target: "@compute"
      services:
         subservice1:
             target: "@compute"
             actions:
                test:
                   cmd: 'uname'
         subservice2:
             target: "@compute"
             actions:
                test:
                   cmd: 'uname'
   service2:
      timeout: 5
      target: "@compute"
      require_filter: [ service1 ]
      actions:
         test:
            cmd: 'uname'
```
