### ISSUE TITLE
issue about tags when used a services in an other services

### ISSUE THREAD

**Issue by geoffrey-guiramand** [cea-hpc/milkcheck#68]
hello,

we try, for a project, to use tags for run specific services. we configured all our tests like :

```
---
services:
  #=============================================================================
  # tags test
  #=============================================================================
  tags.test:
    after: []
    desc: "test for tags"
    require: []
    require_filter: []
    services:
      #=========================================================================
      # the test
      #=========================================================================
      test:
        actions:
          tag-test:
            cmd: |
              echo 0
        after: []
        desc: "the test"
        fanout: 324
        require: []
        require_filter: []       
        target: "@compute"
        timeout: 30
```

But when we use tags : 

```
---
services:
  #=============================================================================
  # tags test
  #=============================================================================
  tags.test:
    after: []
    desc: "test for tags"
    require: []
    require_filter: []
    services:
      #=========================================================================
      # the test
      #=========================================================================
      test:
        actions:
          tag-test:
            cmd: |
              echo 0
        after: []
        desc: "the test"
        fanout: 324
        require: []
        require_filter: []   
        tags: [test]    
        target: "@compute"
        timeout: 30
```

the milkcheck don't do the test : 

```
[root@mngt0-1 step0]# milkcheck tag-test --report=full  -n nod66 -t test

SUMMARY - 0 action (0 failed) 
```

and when I put the tag on the upper service that work :

```
services:
  #=============================================================================
  #  tags test
  #=============================================================================
  tags.test:
    after: []
    desc: "test for tags"
    require: []
    require_filter: []
    services:
      #=========================================================================
      # the test
      #=========================================================================
      test:
        actions:
          tag-test:
            cmd: |
              echo 0
        after: []
        desc: "the test"
        fanout: 324
        require: []
        require_filter: []       
        target: "@compute"
        timeout: 30
    tags: [test]
```

on this situation tags working well.

```
[root@mngt0-1 step0]# milkcheck tag-test --report=full -n nod66 -t test 
tags.test.test - the test                                                                  [    OK   ]
tags.test - test for tags                                                                  [    OK   ] 
SUMMARY - 1 action (0 failed)
+ Success on all services 
pm9-nod66
```
does we use tags on the wrong way ? 

regards,
Geoffrey
